# This is a basic workflow that is manually triggered

name: Manual workflow
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run main.sh
      run: ./main.sh "github actions is cool"
      
